[build]
  command = "pip install -r requirements.txt"
  functions = "functions/"
  # Usaremos un directorio 'public' para los archivos estáticos.
  # Netlify copiará el contenido de 'templates' aquí.
  publish = "public/"

[functions]
  included_files = ["plantilla_informe.docx", "generar_informe.py"]

[[redirects]]
  # Esta regla ahora solo se activa si la página solicitada no existe como archivo estático.
  # Esto permite que /index.html se sirva normalmente.
  # Las llamadas a la API como /generar serán manejadas por la función.
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200 # 200 significa que es una reescritura, no una redirección visible.
