[build]
  command = "pip install -r requirements.txt"
  functions = "functions/"
  # Usaremos un directorio 'public' vacío, ya que la función Flask se encarga de todo.
  publish = "public/"

[functions]
  # Incluimos la plantilla Y la carpeta de templates para que la función pueda acceder a ellos.
  included_files = ["plantilla_informe.docx", "templates/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200 # 200 significa que es una reescritura, no una redirección visible.
