[build]
  command = "pip install -r requirements.txt"
  functions = "functions/"
  # Serviremos los archivos estáticos desde la carpeta 'templates'
  publish = "templates/"

[functions]
  # La plantilla es el único archivo externo que la función necesita
  included_files = ["plantilla_informe.docx"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200 # 200 significa que es una reescritura, no una redirección visible.
