[build]
  command = "pip install -r requirements.txt"
  functions = "functions/"
  publish = "templates/"

[functions]
  included_files = ["plantilla_informe.docx", "generar_informe.py"]

[[redirects]]
  from = "/generar"
  to = "/.netlify/functions/app/generar"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
